version: "3.8"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: georgema8/urlshortner:v1
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        #resources:
         # limits:
          #  cpus: "0.1"
           # memory: 50M
    ports:
      - "4000:80"
      - "8000:8000"
    networks:
      - webnet
    entrypoint: "gunicorn --workers=1 --threads=4 --bind 0.0.0.0:8000 wsgi"
  database_updater:
    # replace username/repo:tag with your name and image details
    image: georgema8/databaseupdater:v1
    deploy:
      replicas: 0
      restart_policy:
        condition: on-failure
        #resources:
         # limits:
          #  cpus: "0.1"
           # memory: 50M
    networks:
      - webnet
  monitor_status:
    # replace username/repo:tag with your name and image details
    image: georgema8/monitorstatus:v1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        #resources:
          # limits:
          #  cpus: "0.1"
            # memory: 50M
    ports:
      - "5000:80"
    volumes:
      - "/home/student/repo_a2group77/exp:/usr/bin/exp"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      # replace /home/docker/data with your data directory
      - "/home/student/repo_a2group77/volumes/redis/data:/data"
      - "/home/student/repo_a2group77/redis.conf:/usr/local/etc/redis/redis.conf"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
  redis-slave:
    image: redis:latest
    command: redis-server --slaveof redis 6379
    depends_on:
      - redis
    volumes:
      # replace /home/docker/data with your data directory
      - "/home/student/repo_a2group77/volumes/redis/data:/data"
      - "/home/student/repo_a2group77/redis.conf:/usr/local/etc/redis/redis.conf"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes    
    networks:
      - webnet
networks:
  webnet:

