version: "3.8"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: georgema8/urlshortner:v1
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
      - "8000:8000"
    volumes:
      - "/home/student/repo_a2group77/volumes/logs:/app/logs"
    networks:
      - webnet
    entrypoint: "gunicorn --workers=2 --threads=4 --log-file=logs/test.log --bind=0.0.0.0:8000 wsgi"
  monitor_status:
    image: georgema8/monitorstatus:v1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    ports:
      - "5000:80"
    volumes:
      - "/home/student/repo_a2group77/exp:/usr/bin/exp"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/student/repo_a2group77/volumes/redis/data:/data"
      - "/home/student/repo_a2group77/redis.conf:/usr/local/etc/redis/redis.conf"
    deploy:
      replicas: 1
      placement:
       constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
  redis-slave:
    image: redis:latest
    command: redis-server --slaveof redis 6379
    depends_on:
      - redis
    volumes:
      - "/home/student/repo_a2group77/volumes/redis/data:/data"
      - "/home/student/repo_a2group77/redis.conf:/usr/local/etc/redis/redis.conf"
    deploy:
      replicas: 1
      placement:
       constraints: [node.role == manager]
    command: redis-server --appendonly yes    
    networks:
      - webnet
networks:
  webnet:

